#!/bin/bash
#PBS -l nodes=01:ppn=16:xk
#PBS -l walltime=2:00:00
#PBS -N project_eval
#PBS -e $PBS_JOBID.err
#PBS -o $PBS_JOBID.out
#PBS -m bea
#PBS -M pacole2@illinois.edu

# cd /u/training/tra247
# ./get_data.sh
cd ~/scratch/cs547_finalproject

. /opt/modules/default/init/bash # NEEDED to add module commands to shell
module load python/2.0.1
# module load bwpy/2.0.0-pre2
# pip3 install --user pycocotools
aprun -n 1 -N 1 python test.py

